---
# tasks file for ansible-arangodb
 - name: Add key for Ubuntu systems
   apt_key: url=https://www.arangodb.com/repositories/arangodb3/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key state=present

 - name: Add repo for Ubuntu systems
   apt_repository: repo='deb https://www.arangodb.com/repositories/arangodb3/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/ /' state=present filename=arangodb
