---
# handlers file for arangodb
- name: reload daemon
  command: systemctl daemon-reload

- name: "restart arangodb"
  service:
    name: "{{arangodb_service_name}}"
    state: restarted
    enabled: yes

- name: "stop arangodb"
  service:
    name: "{{arangodb_service_name}}"
    state: stopped

- name: "start arangodb"
  service:
    name: "{{arangodb_service_name}}"
    state: started
